# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24668fe16ce4158651723c53c6b75a168e534ed54fe6b1f41f411295424a8481bd64c997af13eb155c00bf30c5fbd5067207632a3ea51f188c2383c371062c13

test:
  secret_key_base: 5734bdbe97a6268ff03f54705c92c13be49f28ef2e301692f4eb42f880370c71c3e72a1d81c4b95966e50bfb43510afc25c74696627732880089540afe69a500

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
